import type { Metadata } from "next";
import { AuthContextProvider } from "@/context/AuthContext";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthWrapper from "@/app/_components/AuthWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
