import { AuthContextProvider } from "@/context/AuthContext";
import "./globals.css";
import type { Metadata } from "next";
import ThemeProvider from "@mui/material/styles/ThemeProvider";
import { Inter } from "next/font/google";
import AuthWrapper from "@/components/authentication/AuthWrapper";
import theme from "@/config/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <AuthContextProvider>
            <AuthWrapper>{children}</AuthWrapper>
          </AuthContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
